const PAYMENT_METHODS = Object.freeze({
    PAYPAL: 'PAYPAL',
    CASH: 'CASH',
    BANK_TRANSFER: 'BANK_TRANSFER',
    DOMESTIC_CARD: 'DOMESTIC_CARD',
    VNPAY: 'VNPAY',
    MOMO: 'MOMO',
    PAY_LATER: 'PAY_LATER',
});

const PAYMENT_STATUSES = Object.freeze({
    INITIATED: 'INITIATED',
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
    VOIDED: 'VOIDED',
    REFUNDED: 'REFUNDED',
});

const BOOKING_PAYMENT_STATUS = Object.freeze({
    UNPAID: 'UNPAID',
    PENDING: 'PENDING',
    PAID: 'PAID',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    CANCELLED: 'CANCELLED',
});

module.exports = {
    PAYMENT_METHODS,
    PAYMENT_STATUSES,
    BOOKING_PAYMENT_STATUS,
};

