document.addEventListener('DOMContentLoaded', () => {
    const nav = document.querySelector('.header-nav') || document.querySelector('header nav');
    const userData = JSON.parse(localStorage.getItem('userData') || 'null');
    let currentLang = localStorage.getItem('lang') || 'vi';

    const t = {
        en: {
            becomeHost: 'Host',
            registerText: 'Register',
            myBookings: 'My Bookings',
            welcome: 'Welcome',
            logout: 'Logout',
            login: 'Login',
            tagline: 'Smart Parking Here',
            nav_home: 'Home',
            nav_available: 'Available Spots',
            tab_hourly: 'Hourly/Daily',
            tab_monthly: 'Monthly',
            tab_airport: 'Airport',
            label_park_at: 'Park at',
            label_from: 'From',
            label_until: 'Until',
            btn_show_spaces: 'Show parking spaces',
            why_title: 'Why ParkChung',
            why_subtitle: 'We offer smart parking solutions to save your time, secure your budget, and provide absolute peace of mind.',
            benefit_time_title: 'Save Time',
            benefit_time_desc: 'No worries about risks, your vehicle is protected in a closely monitored area.',
            benefit_price_title: 'Transparent Pricing',
            benefit_price_desc: 'Book in advance, no more endless searching.',
            benefit_safe_title: 'Safe Parking',
            benefit_safe_desc: 'Clear pricing, no surprises when you book.',
            locations_title: 'Featured Locations',
            loc_airports: 'Airports',
            loc_city: 'City Centers',
            loc_homes: 'Private Homes',
            rent_title: 'Rent out your parking or EV charging space',
            rent_desc: 'Make easy tax free money by renting out your parking or EV charging space. It‘s free to list and only takes a few minutes to get up and running.',
            rent_cta: 'Learn how to earn today',
            carpark_title: 'Car park management',
            carpark_desc: 'Maximise yield from underused car parks and vacant land, or transform payments with the favourite parking app.',
            carpark_cta: 'Learn about our solutions',
            press_title: 'The press talks about us',
            footer_contact: 'PARKCHUNG INFORMATION',
            footer_brand: 'Smart Parking Here',
            footer_intro: 'INTRODUCTION',
            footer_subscribe_text: 'Subscribe to receive promotions',
            ph_email: 'Enter your email...',
            btn_signup: 'Sign-up',
            footer_policies: 'POLICIES',
            pol_privacy: 'Privacy Policy',
            pol_terms: 'Service Regulations',
            pol_incidents: 'Incidents & Complaints',
            pol_host: 'Become a Host',
            footer_support: 'SUPPORT',
            sup_booking: 'Parking Booking Guide',
            sup_listing: 'Parking Listing Guide',
            sup_faq: 'FAQs',
            sup_blog: 'Blog',
            footer_copy: 'Copyright © 2026 ParkChung. All rights reserved.',
            ph_location: 'Enter a place or postcode',
            results_title: 'Available Parking Spots',
            results_desc: 'Choose the best spot for you and book in seconds.',
            no_results: 'Sorry, no available parking spots were found for your criteria.',
            book_now: 'Book Now',
            login_title: 'Login to Your Account',
            register_title: 'Create Your Account',
            email: 'Email',
            password: 'Password',
            full_name: 'Full Name',
            phone: 'Phone',
            register: 'Register',
            no_account: "Don't have an account?",
            register_here: 'Register here',
            have_account: 'Already have an account?',
            login_here: 'Login here',
            my_bookings: 'My Bookings',
            back_home: '← Back to Home',
            loading: 'Loading your bookings...',
            host_hero_title: 'Earn Money with Your Parking Space',
            host_hero_desc: "Join our community of hosts and turn your unused parking spot into a source of income. It's simple, secure, and free to list.",
            host_benefit_price: 'Set your own price',
            host_benefit_avail: 'Control your availability',
            host_benefit_secure: 'Secure and easy payments',
            host_form_title: 'List Your Spot',
            host_form_note: 'Your spot will be reviewed by an admin before being published.',
            address: 'Address',
            get_location: 'Get Location',
            coords_hint: "We'll try to get your coordinates automatically. You can adjust them manually if needed.",
            longitude: 'Longitude',
            latitude: 'Latitude',
            hourly_rate: 'Hourly Rate (VND)',
            spot_image: 'Image of Your Spot',
            click_upload: 'Click to Upload Image',
            no_file: 'No file chosen',
            submit_review: 'Submit for Review',
            details_title: 'Spot Details',
            details_subtitle: "You're almost done! Just a few more details to confirm your booking.",
            details_section_title: 'Booking details',
            arriving_on: 'Arriving on',
            leaving_on: 'Leaving on',
            ph_select_datetime: 'Select Date/Time',
            duration: 'Duration',
            contact_title: "Customer's information",
            contact_phone_label: 'Phone Number',
            contact_hint: 'We\'ll use this to contact you about your booking',
            vehicle_title: 'Vehicle Information',
            vehicle_reg_label: 'Vehicle Registration',
            vehicle_desc: 'Your vehicle registration will be shared with the parking operator',
            ph_vehicle_reg: 'Enter your vehicle registration',
            payment_title: 'Payment Information',
            payment_desc: 'All payments are secure and encrypted with bank-level security',
            payment_secure: '256-bit SSL encryption',
            payment_methods: 'All major cards accepted',
            spot_loading: 'Loading Address...',
            unit_price: 'Unit Price',
            parking_duration: 'Parking Duration',
            total_price: 'Total Price',
            rechecked: 'Availability rechecked in',
            time_to_complete: 'Time to complete booking:',
            btn_pay_reserve: 'Pay now and reserve',
            trust_transparent_pricing: 'Transparent pricing shown before you confirm',
            trust_verified_hosts: 'Verified hosts & clear listing rules',
            trust_flexible_payment: 'Flexible payment options: online (eligible listings) or cash on arrival',
            trust_free_cancel: 'Free cancellation on eligible bookings — see the listing',
            trust_support: 'Fast, reliable customer support when you need help',
            trust_excellent: 'Excellent',
            popup_title: 'Complete Your Booking',
            popup_booking_summary: 'Booking Summary',
            popup_from: 'From',
            popup_to: 'To',
            popup_contact_info: 'Contact Information',
            popup_contact_desc: 'We\'ll use this information to confirm your booking',
            popup_fullname: 'Full Name',
            popup_email: 'Email Address',
            popup_phone: 'Phone Number',
            popup_cancel: 'Cancel',
            popup_send: 'Complete Booking',
            // Booking config page
            becomeHostRegister: 'Become a Host / Register',
            config_title: 'Complete Your Booking',
            config_subtitle: 'Just a few more details to confirm your reservation.',
            contact_fullname_label: 'Full Name',
            contact_email_label: 'Email Address',
            ph_fullname: 'Enter your full name',
            terms: 'Clicking below indicates that you have read and accept the Terms & Conditions',
            btn_reserve: 'Reserve Now',
            // Filter sidebar
            filter_title: 'Filters',
            filter_clear: 'Clear All',
            filter_vehicle_type: 'Vehicle Type',
            filter_car: 'Car',
            filter_motorbike: 'Motorbike',
            filter_bicycle: 'Bicycle',
            filter_truck: 'Truck / Large Vehicle',
            filter_booking_type: 'Booking Type',
            filter_online: 'Online Booking',
            filter_call: 'Call Booking',
            filter_payment: 'Payment Methods',
            filter_cash: 'Cash',
            filter_paypal: 'PayPal',
            // Spot Details page
            by_google_rating: 'By GoogleRating',
            spot_description: 'Description',
            no_description: 'No description available for this parking spot.',
            spot_location: 'Location',
            view_on_maps: 'View on Google Maps',
            pricing_capacity: 'Pricing & Capacity',
            hourly_rate_label: 'Hourly Rate',
            vnd_per_hour: 'VND/hour',
            monthly_rate_label: 'Monthly Rate',
            not_available: 'Not available',
            available_slots: 'Available Slots',
            unknown: 'Unknown',
            vehicle_types_accepted: 'Vehicle Types Accepted',
            accepted_payment_methods: 'Accepted Payment Methods',
            services_title: 'Services',
            no_services: 'No additional services available',
            call_to_book: 'Call to Book',
            // Payment method labels
            payment_method_title: 'Payment Method',
            pay_securely_online: 'Pay securely online',
            cash_pay_later: 'Cash / Pay Later',
            pay_at_spot: 'Pay at parking spot',
            badge_instant: 'Instant',
            badge_flexible: 'Flexible'
        },
        vi: {
            becomeHost: 'Trở thành chủ bãi đậu xe',
            registerText: 'Đăng ký',
            myBookings: 'Đặt chỗ của tôi',
            welcome: 'Xin chào',
            logout: 'Đăng xuất',
            login: 'Đăng nhập',
            tagline: 'Smart Parking Here',
            nav_home: 'Trang chủ',
            nav_available: 'Chỗ trống',
            tab_hourly: 'Theo giờ/Ngày',
            tab_monthly: 'Theo tháng',
            tab_airport: 'Sân bay',
            label_park_at: 'Đỗ tại',
            label_from: 'Từ',
            label_until: 'Đến',
            btn_show_spaces: 'Hiển thị chỗ đỗ',
            why_title: 'Vì sao chọn ParkChung',
            why_subtitle: 'Chúng tôi mang đến giải pháp đỗ xe thông minh, giúp bạn tiết kiệm thời gian, an tâm về chi phí và yên tâm tuyệt đối khi gửi xe.',
            benefit_time_title: 'Tiết kiệm thời gian',
            benefit_time_desc: 'Không lo rủi ro, phương tiện được bảo vệ trong khu vực giám sát chặt chẽ',
            benefit_price_title: 'Giá cả minh bạch',
            benefit_price_desc: 'Đặt chỗ trước, không còn mất công tìm kiếm.',
            benefit_safe_title: 'Bãi đỗ an toàn',
            benefit_safe_desc: 'Giá rõ ràng, không phát sinh phụ phí bất ngờ.',
            locations_title: 'Địa điểm nổi bật',
            loc_airports: 'Sân bay',
            loc_city: 'Trung tâm thành phố',
            loc_homes: 'Nhà riêng',
            rent_title: 'Cho thuê chỗ đỗ hoặc điểm sạc EV của bạn',
            rent_desc: 'Tạo thu nhập dễ dàng, miễn thuế từ chỗ đỗ/điểm sạc của bạn. Đăng tin miễn phí và chỉ mất vài phút để bắt đầu.',
            rent_cta: 'Tìm hiểu cách kiếm tiền ngay',
            carpark_title: 'Quản lý bãi đỗ xe',
            carpark_desc: 'Tối đa hóa công suất bãi đỗ và tối ưu thanh toán với ứng dụng ưa thích.',
            carpark_cta: 'Tìm hiểu giải pháp',
            press_title: 'Báo chí nói về chúng tôi',
            footer_contact: 'THÔNG TIN PARKCHUNG',
            footer_brand: 'Smart Parking Here',
            footer_intro: 'GIỚI THIỆU',
            footer_subscribe_text: 'Đăng ký nhận khuyến mãi',
            ph_email: 'Nhập email của bạn...',
            btn_signup: 'Đăng ký',
            footer_policies: 'CHÍNH SÁCH',
            pol_privacy: 'Chính sách bảo mật',
            pol_terms: 'Quy định dịch vụ',
            pol_incidents: 'Sự cố & Khiếu nại',
            pol_host: 'Trở thành Chủ bãi',
            footer_support: 'HỖ TRỢ',
            sup_booking: 'Hướng dẫn đặt chỗ',
            sup_listing: 'Hướng dẫn đăng bãi',
            sup_faq: 'Câu hỏi thường gặp',
            sup_blog: 'Blog',
            footer_copy: 'Bản quyền © 2026 thuộc Parkchung. Bảo lưu mọi quyền.',
            ph_location: 'Nhập địa điểm hoặc mã bưu chính',
            results_title: 'Chỗ đỗ xe khả dụng',
            results_desc: 'Chọn chỗ phù hợp và đặt trong vài giây.',
            no_results: 'Rất tiếc, không tìm thấy chỗ đỗ phù hợp với tiêu chí của bạn.',
            book_now: 'Đặt ngay',
            login_title: 'Đăng nhập tài khoản',
            register_title: 'Tạo tài khoản',
            email: 'Email',
            password: 'Mật khẩu',
            full_name: 'Họ và tên',
            phone: 'Số điện thoại',
            register: 'Đăng ký',
            no_account: 'Chưa có tài khoản?',
            register_here: 'Đăng ký tại đây',
            have_account: 'Đã có tài khoản?',
            login_here: 'Đăng nhập tại đây',
            my_bookings: 'Đặt chỗ của tôi',
            back_home: '← Về Trang chủ',
            loading: 'Đang tải danh sách đặt chỗ...',
            host_hero_title: 'Kiếm tiền với chỗ đỗ xe của bạn',
            host_hero_desc: 'Tham gia cộng đồng chủ bãi và biến chỗ đỗ trống thành thu nhập. Đơn giản, an toàn và miễn phí đăng tin.',
            host_benefit_price: 'Tự đặt giá',
            host_benefit_avail: 'Chủ động lịch trống',
            host_benefit_secure: 'Thanh toán an toàn, dễ dàng',
            host_form_title: 'Đăng tin chỗ đỗ',
            host_form_note: 'Tin sẽ được quản trị viên duyệt trước khi hiển thị.',
            address: 'Địa chỉ',
            get_location: 'Lấy vị trí',
            coords_hint: 'Chúng tôi sẽ cố gắng lấy tọa độ tự động. Bạn có thể chỉnh thủ công nếu cần.',
            longitude: 'Kinh độ',
            latitude: 'Vĩ độ',
            hourly_rate: 'Giá theo giờ (VND)',
            spot_image: 'Hình ảnh chỗ đỗ',
            click_upload: 'Nhấn để tải ảnh lên',
            no_file: 'Chưa chọn tệp',
            submit_review: 'Gửi duyệt',
            details_title: 'CHI TIẾT ĐẶT CHỖ',
            details_subtitle: 'Bạn sắp hoàn tất! Vui lòng điền vài thông tin để xác nhận.',
            details_section_title: 'Chi tiết đặt chỗ',
            arriving_on: 'Thời gian đến',
            leaving_on: 'Thời gian rời đi',
            ph_select_datetime: 'Chọn ngày/giờ',
            duration: 'Số giờ đặt chỗ',
            contact_title: 'Số điện thoại',
            contact_phone_label: 'Số Điện Thoại',
            contact_hint: 'Chúng tôi sẽ sử dụng thông tin này để liên hệ với bạn về đặt chỗ',
            vehicle_title: 'Thông Tin Phương Tiện',
            vehicle_reg_label: 'Biển Số Xe',
            vehicle_desc: 'Biển số xe của bạn sẽ được chia sẻ với đơn vị vận hành bãi đỗ',
            ph_vehicle_reg: 'Nhập biển số xe của bạn',
            payment_title: 'Thông Tin Thanh Toán',
            payment_desc: 'Tất cả thanh toán đều được mã hóa và bảo mật ở mức ngân hàng',
            payment_secure: 'Mã hóa SSL 256-bit',
            payment_methods: 'Chấp nhận tất cả thẻ chính',
            spot_loading: 'Đang tải địa chỉ...',
            unit_price: 'Đơn giá',
            parking_duration: 'Thời lượng đỗ',
            total_price: 'Tổng tiền',
            rechecked: 'Kiểm tra lại khả dụng lúc',
            time_to_complete: 'Thời gian hoàn tất đặt chỗ:',
            btn_pay_reserve: 'Thanh toán và giữ chỗ',
            trust_transparent_pricing: 'Giá minh bạch được hiển thị trước khi xác nhận',
            trust_verified_hosts: 'Chủ bãi đã xác minh & quy định rõ ràng',
            trust_flexible_payment: 'Tùy chọn thanh toán linh hoạt: trực tuyến (danh sách đủ điều kiện) hoặc tiền mặt khi đến',
            trust_free_cancel: 'Hủy miễn phí cho đặt chỗ đủ điều kiện — xem danh sách',
            trust_support: 'Hỗ trợ khách hàng nhanh chóng, đáng tin cậy khi bạn cần',
            trust_excellent: 'Xuất sắc',
            popup_title: 'Hoàn Tất Đặt Chỗ',
            popup_booking_summary: 'Tóm Tắt Đặt Chỗ',
            popup_from: 'Từ',
            popup_to: 'Đến',
            popup_contact_info: 'Thông Tin Liên Hệ',
            popup_contact_desc: 'Chúng tôi sẽ sử dụng thông tin này để xác nhận đặt chỗ của bạn',
            popup_fullname: 'Họ và Tên',
            popup_email: 'Địa Chỉ Email',
            popup_phone: 'Số Điện Thoại',
            popup_cancel: 'Hủy',
            popup_send: 'Hoàn Tất Đặt Chỗ',
            // Trang cấu hình đặt chỗ
            becomeHostRegister: 'Trở thành Chủ bãi / Đăng ký',
            config_title: 'Hoàn Tất Đặt Chỗ',
            config_subtitle: 'Chỉ cần vài thông tin nữa để xác nhận đặt chỗ của bạn.',
            contact_fullname_label: 'Họ và Tên',
            contact_email_label: 'Địa chỉ Email',
            ph_fullname: 'Nhập họ và tên của bạn',
            terms: 'Nhấn bên dưới nghĩa là bạn đã đọc và chấp nhận Điều khoản & Điều kiện',
            btn_reserve: 'Đặt Ngay',
            // Bộ lọc
            filter_title: 'Bộ lọc',
            filter_clear: 'Xóa tất cả',
            filter_vehicle_type: 'Loại phương tiện',
            filter_car: 'Ô tô',
            filter_motorbike: 'Xe máy',
            filter_bicycle: 'Xe đạp',
            filter_truck: 'Xe tải / Xe lớn',
            filter_booking_type: 'Loại đặt chỗ',
            filter_online: 'Đặt trực tuyến',
            filter_call: 'Đặt qua điện thoại',
            filter_payment: 'Phương thức thanh toán',
            filter_cash: 'Tiền mặt',
            filter_paypal: 'PayPal',
            // Trang chi tiết chỗ đỗ
            by_google_rating: 'Theo GoogleRating',
            spot_description: 'Mô tả',
            no_description: 'Không có mô tả cho chỗ đỗ xe này.',
            spot_location: 'Vị trí',
            view_on_maps: 'Xem trên Google Maps',
            pricing_capacity: 'Giá & Chỗ trống',
            hourly_rate_label: 'Giá theo giờ',
            vnd_per_hour: 'VND/giờ',
            monthly_rate_label: 'Giá theo tháng',
            not_available: 'Không khả dụng',
            available_slots: 'Chỗ trống',
            unknown: 'Không rõ',
            vehicle_types_accepted: 'Loại phương tiện được chấp nhận',
            accepted_payment_methods: 'Phương thức thanh toán được chấp nhận',
            services_title: 'Dịch vụ',
            no_services: 'Không có dịch vụ bổ sung',
            call_to_book: 'Gọi để đặt chỗ',
            // Nhãn phương thức thanh toán
            payment_method_title: 'Phương thức thanh toán',
            pay_securely_online: 'Thanh toán an toàn trực tuyến',
            cash_pay_later: 'Tiền mặt / Thanh toán sau',
            pay_at_spot: 'Thanh toán tại bãi đỗ',
            badge_instant: 'Ngay lập tức',
            badge_flexible: 'Linh hoạt'
        }
    };

    Object.assign(t.en, {
        my_profile: 'My Profile',
        billed_as: 'Billed as',
        billing_info: 'Bookings are charged in 1-hour blocks (minimum 1 hour).',
        footer_about: 'About Us',
        about_footer_address_1: 'Address: BK Alumni House,',
        about_footer_address_2: 'Hanoi University of Science and Technology,',
        about_footer_address_3: 'No. 1 Dai Co Viet street, Hanoi',
        pol_terms_service: 'Terms of Service',
        pol_insurance: 'Insurance & Liability Policy',
        pol_dispute: 'Dispute Resolution Policy',
        pol_security: 'Security Policy',
        pol_driver: 'Driver Terms & Booking Policies',
        pol_supplier: 'Supplier Terms & Policies',
        terms_prefix: 'Clicking below indicates that you have read and accept the',
        terms_link: 'Terms & Conditions',
        about_page_title: 'About Us',
        about_intro_para1: 'Parkchung is a pioneering startup developing an online platform for self-driving car and motorbike rental and sharing in Vietnam.',
        about_intro_para2: 'Parkchung connects customers needing to rent self-driving vehicles (cars, motorbikes) with rental units and individuals with idle vehicles nationwide via its website or mobile app, allowing easy and quick searching, comparing, and renting.',
        about_intro_para3: 'Parkchung\'s mission is to provide a modern technology platform for fast, safe, and economical vehicle rental and sharing, aiming for a civilized and environmentally friendly community for vehicle sharing.',
        about_why_title: 'Why do we do it?',
        about_why_item1: 'Currently, in Vietnam, there is no online platform for renting and sharing motorbikes, self-driving cars.',
        about_why_item2: 'Car renters face many difficulties in renting a self-driving car as desired, while individuals with idle cars or self-driving car rental units do not have good enough technology to manage and optimize their assets.',
        about_why_item3: 'With the explosion of the 4.0 technology trend, the conveniences of booking transportation services via online/mobile channels as well as car-sharing technology are increasingly developing and becoming popular.',
        about_why_item4: 'Vehicle sharing is gradually becoming the main trend in the world, replacing vehicle ownership.',
        about_how_title: 'How do we do it?',
        about_how_para1: 'Even the most complex problems have a suitable solution. Parkchung doesn\'t just rent cars; it creates innovative products within the existing ecosystem.',
        about_how_para2: 'We leverage technology to provide a comprehensive travel solution by connecting customers with self-drive car rental service providers. Parkchung\'s mission is to offer a platform where customers can easily rent their desired car, while car owners can attract customers and conduct business conveniently.',
        about_how_para3: 'The company focuses on simplifying the car rental process, offering transaction support tools from price comparison to online payment, car rental insurance, reduced procedures, and many other utilities for both customers and car-providing partners.',
        
        // V3 HOMEPAGE REDESIGN
        becomeHost: 'Become a Partner <i class="fas fa-chevron-down" style="font-size: 0.7rem; margin-left: 3px; vertical-align: middle; color: #2DC989;"></i>',
        hero_title: 'Optimize your journey with smart parking pre-booking',
        label_dropoff: 'DROP OFF AT',
        label_pickup: 'PICK UP AT',
        why_subtitle: 'We provide smart parking solutions, helping you save time, be peace of mind about costs, and feel absolutely secure when parking.',
        eco_title: 'ParkChung Ecosystem',
        eco_coop_title: 'Partner with ParkChung – Optimize parking revenue',
        eco_f1: 'Turn your vacant parking spaces into daily passive income sources',
        eco_f2: 'Manage bookings and track transparent revenues directly on the app',
        eco_f3: 'Instantly connect with a network of active drivers looking for parking',
        eco_cta: 'Learn more',
        quote_text: 'Giải pháp đỗ xe càng thuận tiện, hành trình càng trở nên dễ dàng và chúng ta càng gắn kết với nhau hơn.',
        quote_author_name: 'BRANNAN COADY',
        quote_author_title: 'CEO',
        press_title: 'What the press says about us',
        press_badge: 'PRESS',
        press_subtitle: 'What journalists say about our solution. We are proud to share the journey.',
        press_read_article: 'Read Article ↗',
        press_article1_source: 'UNDP VIETNAM · VIETCHALLENGE 2019',
        press_article2_source: 'UNDP VIETNAM · VIETCHALLENGE 2019',
        press_article3_source: 'UNDP VIETNAM · VIETCHALLENGE 2019',
        press_article1_title: 'Chúc mừng 12 startup chính thức bước vào giai đoạn đào tạo chuyên sâu của Chương trình ươm tạo Việt Nam - Nhật Bản!',
        press_article2_title: 'Chúc mừng 12 startup chính thức bước vào giai đoạn đào tạo chuyên sâu của Chương trình ươm tạo Việt Nam - Nhật Bản!',
        press_article3_title: 'Chúc mừng 12 startup chính thức bước vào giai đoạn đào tạo chuyên sâu của Chương trình ươm tạo Việt Nam - Nhật Bản!',
        review_1_text: 'Việc đỗ xe tại Nhà ga số 5 sân bay Nội Bài quá đỗi dễ dàng. Cực kỳ dễ tìm và siêu RẺ! Chắc chắn tôi sẽ tiếp tục sử dụng dịch vụ! Cảm ơn.',
        review_2_text: 'Việc đỗ xe tại Nhà ga số 5 sân bay Nội Bài quá đỗi dễ dàng. Cực kỳ dễ tìm và siêu RẺ! Chắc chắn tôi sẽ tiếp tục sử dụng dịch vụ! Cảm ơn.',
        review_3_text: 'Việc đỗ xe tại Nhà ga số 5 sân bay Nội Bài quá đỗi dễ dàng. Cực kỳ dễ tìm và siêu RẺ! Chắc chắn tôi sẽ tiếp tục sử dụng dịch vụ! Cảm ơn.',
        review_4_text: 'Việc đỗ xe tại Nhà ga số 5 sân bay Nội Bài quá đỗi dễ dàng. Cực kỳ dễ tìm và siêu RẺ! Chắc chắn tôi sẽ tiếp tục sử dụng dịch vụ! Cảm ơn.',
        review_5_text: 'Việc đỗ xe tại Nhà ga số 5 sân bay Nội Bài quá đỗi dễ dàng. Cực kỳ dễ tìm và siêu RẺ! Chắc chắn tôi sẽ tiếp tục sử dụng dịch vụ! Cảm ơn.',
        review_1_author: 'Phong Anh',
        review_2_author: 'Phong Anh',
        review_3_author: 'Phong Anh',
        review_4_author: 'Phong Anh',
        review_5_author: 'Phong Anh',
        review_1_role: 'Service User',
        review_2_role: 'Service User',
        review_3_role: 'Service User',
        review_4_role: 'Service User',
        review_5_role: 'Service User',
        footer_subscribe_text: 'Subscribe to promotions',
        footer_follow_us: 'FOLLOW US',
        footer_contact: 'PARKCHUNG INFORMATION',
        footer_copy: 'Copyright © 2026 ParkChung. All rights reserved.'
    });

    Object.assign(t.vi, {
        my_profile: 'Hồ sơ của tôi',
        billed_as: 'Tính phí theo',
        billing_info: 'Đặt chỗ được tính theo block 1 giờ (tối thiểu 1 giờ).',
        footer_about: 'About us',
        about_footer_address_1: 'Địa chỉ: Nhà Cựu sinh viên BK,',
        about_footer_address_2: 'Trường Đại học Bách khoa Hà Nội,',
        about_footer_address_3: 'Số 1 Đại Cồ Việt, Hà Nội',
        pol_terms_service: 'Terms of Service',
        pol_insurance: 'Insurance & Liability Policy',
        pol_dispute: 'Dispute Resolution Policy',
        pol_security: 'Security Policy',
        pol_driver: 'Driver Terms & Booking Policies',
        pol_supplier: 'Supplier Terms & Policies',
        terms_prefix: 'Nhấn nút bên dưới đồng nghĩa bạn đã đọc và đồng ý với',
        terms_link: 'Điều khoản & Điều kiện',
        about_page_title: 'Về chúng tôi',
        about_intro_para1: 'Parkchung là startup tiên phong phát triển nền tảng trực tuyến cho thuê và chia sẻ ô tô, xe máy tự lái tại Việt Nam.',
        about_intro_para2: 'Parkchung kết nối khách hàng có nhu cầu thuê xe tự lái (ô tô, xe máy) với các đơn vị cho thuê và cá nhân có phương tiện nhàn rỗi trên toàn quốc thông qua website hoặc ứng dụng di động, giúp việc tìm kiếm, so sánh và thuê xe trở nên dễ dàng, nhanh chóng.',
        about_intro_para3: 'Sứ mệnh của Parkchung là cung cấp nền tảng công nghệ hiện đại cho hoạt động thuê và chia sẻ phương tiện nhanh chóng, an toàn, tiết kiệm, hướng tới một cộng đồng văn minh và thân thiện với môi trường.',
        about_why_title: 'Vì sao chúng tôi làm điều này?',
        about_why_item1: 'Hiện tại tại Việt Nam chưa có nền tảng trực tuyến chuyên cho thuê và chia sẻ xe máy, ô tô tự lái.',
        about_why_item2: 'Người thuê xe gặp nhiều khó khăn khi tìm xe tự lái đúng nhu cầu, trong khi cá nhân có xe nhàn rỗi hoặc đơn vị cho thuê lại chưa có công nghệ đủ tốt để quản lý và tối ưu tài sản.',
        about_why_item3: 'Cùng với làn sóng công nghệ 4.0, việc đặt dịch vụ vận chuyển qua kênh online/mobile và công nghệ chia sẻ xe ngày càng phát triển, phổ biến hơn.',
        about_why_item4: 'Chia sẻ phương tiện đang dần trở thành xu hướng chủ đạo trên thế giới, thay thế cho việc sở hữu phương tiện.',
        about_how_title: 'Chúng tôi thực hiện như thế nào?',
        about_how_para1: 'Ngay cả những bài toán phức tạp nhất cũng có lời giải phù hợp. Parkchung không chỉ cho thuê xe mà còn tạo ra những sản phẩm đổi mới trong hệ sinh thái sẵn có.',
        about_how_para2: 'Chúng tôi tận dụng công nghệ để cung cấp giải pháp di chuyển toàn diện bằng cách kết nối khách hàng với các đơn vị cung cấp dịch vụ cho thuê xe tự lái. Parkchung hướng tới một nền tảng nơi khách hàng dễ dàng thuê đúng chiếc xe mong muốn, còn chủ xe có thể tiếp cận khách hàng và kinh doanh thuận tiện.',
        about_how_para3: 'Công ty tập trung đơn giản hóa quy trình thuê xe, cung cấp các công cụ hỗ trợ giao dịch từ so sánh giá, thanh toán trực tuyến, bảo hiểm thuê xe, tinh gọn thủ tục đến nhiều tiện ích khác cho cả khách hàng lẫn đối tác cung cấp xe.',
        
        // V3 HOMEPAGE REDESIGN
        becomeHost: 'Trở thành chủ bãi đậu xe <i class="fas fa-chevron-down" style="font-size: 0.7rem; margin-left: 3px; vertical-align: middle; color: #2DC989;"></i>',
        hero_title: 'Tối ưu hóa hành trình với giải pháp đặt trước bãi đỗ thông minh',
        label_dropoff: 'GIAO XE TẠI',
        label_pickup: 'ĐIỂM TRẢ XE',
        why_subtitle: 'Chúng tôi mang đến giải pháp đỗ xe thông minh, giúp bạn tiết kiệm thời gian, an tâm về chi phí và yên tâm tuyệt đối khi gửi xe.',
        eco_title: 'Hệ sinh thái của ParkChung',
        eco_coop_title: 'Hợp tác cùng ParkChung – Tối ưu thu nhập bãi đỗ',
        eco_f1: 'Biến những vị trí đỗ xe trống thành nguồn thu nhập thụ động mỗi ngày',
        eco_f2: 'Quản lý đặt chỗ và theo dõi doanh thu minh bạch ngay trên ứng dụng',
        eco_f3: 'Tiếp cận tức thì mạng lưới tài xế đang tìm kiếm chỗ đỗ',
        eco_cta: 'Tìm hiểu ngay',
        quote_text: 'Giải pháp đỗ xe càng thuận tiện, hành trình càng trở nên dễ dàng và chúng ta càng gắn kết với nhau hơn.',
        quote_author_name: 'BRANNAN COADY',
        quote_author_title: 'CEO',
        press_title: 'Báo chí nói gì về chúng tôi',
        press_badge: 'BÁO CHÍ',
        press_subtitle: 'Cảm nhận của các nhà báo về giải pháp của chúng tôi. Chúng tôi tự hào được chia sẻ hành trình.',
        press_read_article: 'Đọc bài viết ↗',
        press_article1_source: 'UNDP VIETNAM · VIETCHALLENGE 2019',
        press_article2_source: 'UNDP VIETNAM · VIETCHALLENGE 2019',
        press_article3_source: 'UNDP VIETNAM · VIETCHALLENGE 2019',
        press_article1_title: 'Chúc mừng 12 startup chính thức bước vào giai đoạn đào tạo chuyên sâu của Chương trình ươm tạo Việt Nam - Nhật Bản!',
        press_article2_title: 'Chúc mừng 12 startup chính thức bước vào giai đoạn đào tạo chuyên sâu của Chương trình ươm tạo Việt Nam - Nhật Bản!',
        press_article3_title: 'Chúc mừng 12 startup chính thức bước vào giai đoạn đào tạo chuyên sâu của Chương trình ươm tạo Việt Nam - Nhật Bản!',
        review_1_text: 'Việc đỗ xe tại Nhà ga số 5 sân bay Nội Bài quá đỗi dễ dàng. Cực kỳ dễ tìm và siêu RẺ! Chắc chắn tôi sẽ tiếp tục sử dụng dịch vụ! Cảm ơn.',
        review_2_text: 'Việc đỗ xe tại Nhà ga số 5 sân bay Nội Bài quá đỗi dễ dàng. Cực kỳ dễ tìm và siêu RẺ! Chắc chắn tôi sẽ tiếp tục sử dụng dịch vụ! Cảm ơn.',
        review_3_text: 'Việc đỗ xe tại Nhà ga số 5 sân bay Nội Bài quá đỗi dễ dàng. Cực kỳ dễ tìm và siêu RẺ! Chắc chắn tôi sẽ tiếp tục sử dụng dịch vụ! Cảm ơn.',
        review_4_text: 'Việc đỗ xe tại Nhà ga số 5 sân bay Nội Bài quá đỗi dễ dàng. Cực kỳ dễ tìm và siêu RẺ! Chắc chắn tôi sẽ tiếp tục sử dụng dịch vụ! Cảm ơn.',
        review_5_text: 'Việc đỗ xe tại Nhà ga số 5 sân bay Nội Bài quá đỗi dễ dàng. Cực kỳ dễ tìm và siêu RẺ! Chắc chắn tôi sẽ tiếp tục sử dụng dịch vụ! Cảm ơn.',
        review_1_author: 'Phong Anh',
        review_2_author: 'Phong Anh',
        review_3_author: 'Phong Anh',
        review_4_author: 'Phong Anh',
        review_5_author: 'Phong Anh',
        review_1_role: 'Người sử dụng dịch vụ',
        review_2_role: 'Người sử dụng dịch vụ',
        review_3_role: 'Người sử dụng dịch vụ',
        review_4_role: 'Người sử dụng dịch vụ',
        review_5_role: 'Người sử dụng dịch vụ',
        footer_subscribe_text: 'Đăng ký nhận khuyến mãi',
        footer_follow_us: 'THEO DÕI CHÚNG TÔI',
        footer_contact: 'THÔNG TIN PARKCHUNG',
        footer_brand: 'Smart Parking Here',
        footer_policies: 'CHÍNH SÁCH',
        footer_copy: 'Bản quyền © 2026 thuộc Parkchung. Bảo lưu mọi quyền.'
    });

    function renderNav() {
        const dict = t[currentLang] || t.en;
        const langFlag = currentLang === 'vi'
            ? 'https://flagcdn.com/w40/vn.png'
            : 'https://flagcdn.com/w40/gb.png';
        const langSwitcher = `
            <div class="lang-switcher" id="lang-switcher-nav">
                <img src="${langFlag}" alt="${currentLang.toUpperCase()}" class="lang-flag" />
                <span class="lang-arrow">▼</span>
            </div>
        `;

        if (userData) {
            nav.innerHTML = `
                <a href="${window.HOST_URL}/login" class="nav-link become-host-link">${dict.becomeHost}</a>
                <a href="my-bookings.html" class="nav-link">${dict.myBookings}</a>
                <a href="my-profile.html" class="nav-link">${dict.my_profile}</a>
                <span class="nav-link" style="cursor:default;">${dict.welcome}, ${userData.fullName}!</span>
                <a href="#" id="logout-btn" class="btn-nav btn-nav-outline" style="border-color:#e74c3c;color:#e74c3c;">${dict.logout}</a>
                ${langSwitcher}
            `;
        } else {
            nav.innerHTML = `
                <a href="${window.HOST_URL}/login" class="nav-link become-host-link">${dict.becomeHost}</a>
                <a href="login.html" class="btn-nav btn-nav-primary">${dict.login}</a>
                <a href="register.html" class="nav-link register-link" style="color: #2DC989; font-weight: 500; font-family: 'Montserrat Alternates', sans-serif; font-size: 16px; margin-left: 12px;">${dict.registerText}</a>
                ${langSwitcher}
            `;
        }

        const logoutBtn = document.getElementById('logout-btn');
        if (logoutBtn) {
            logoutBtn.addEventListener('click', (e) => {
                e.preventDefault();
                localStorage.removeItem('userToken');
                localStorage.removeItem('userData');
                window.location.href = 'index.html';
            });
        }

        const langSwitcherEl = document.getElementById('lang-switcher-nav');
        if (langSwitcherEl) {
            langSwitcherEl.addEventListener('click', () => {
                setLanguage(currentLang === 'vi' ? 'en' : 'vi');
            });
        }

        applyTranslations(dict);
        window.__applyI18n = () => applyTranslations(t[currentLang] || t.en);
    }

    function setLanguage(lang) {
        localStorage.setItem('lang', lang);
        currentLang = lang;
        renderNav();
    }

    function applyTranslations(dict) {
        // Text content
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (dict[key]) el.textContent = dict[key];
        });
        // Placeholders
        document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
            const key = el.getAttribute('data-i18n-placeholder');
            if (dict[key]) el.setAttribute('placeholder', dict[key]);
        });
    }

    renderNav();
});
